services:
  epg:
    image: ghcr.io/iptv-org/epg:master
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/epg/public

  xmltv-api:
    build: .
    restart: always
    ports:
      - "3001:3001"
    environment:
      - EPG_URL=http://epg:3000/guide.xml
      - REFRESH_INTERVAL_MS=3600000
    depends_on:
      - epg